# Generated by Django 5.0.4 on 2024-05-04 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='course',
            name='professor',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='course',
            name='seats',
            field=models.IntegerField(db_index=True, default=30),
        ),
    ]
