# Generated by Django 5.0.4 on 2024-05-04 20:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_course_name_alter_course_professor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='name',
            field=models.CharField(db_index=True, max_length=255, validators=[django.core.validators.RegexValidator(regex='^Faculty of')]),
        ),
        migrations.AlterField(
            model_name='student',
            name='average_grade',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
    ]
