# Generated by Django 5.0.4 on 2024-05-09 21:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_professor_alter_course_professor'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='current_course',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)]),
        ),
    ]
