# Generated by Django 5.0.4 on 2024-05-13 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_courseapplication_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseapplication',
            name='semester',
            field=models.IntegerField(choices=[(3, '3rd Semester'), (4, '4th Semester'), (5, '5th Semester'), (6, '6th Semester'), (7, '7th Semester'), (8, '8th Semester')], default=3),
        ),
    ]
